# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b7ee2233dfafd51a7a2ed229b1f477586939cea0367543ff34ffc5d4451b2ac5f8cd5c9699c6aa55a455e6cc75a0f2b06a7e9748be2ff02c4508a845651911e

test:
  secret_key_base: 8f4d0d5e9697db551e918a58e8c0f8c38931eff3fc615a4d962f4e9b3dfbb0ca0f489c90070b10bb53f5fc217ea9f3b97e1648fa265b7c0ac6f28424de71f874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
